os:
  - osx

script:
  - brew tap nrobinson2000/po
  - brew install po
  - ./config-expect.sh
  - po install
  - mkdir test && cd test && po init
  - time po photon build
  - time po electron clean
  - time po electron build
  - time po P1 clean
  - time po P1 build
  - time po core clean
  - time po core build
